### ISSUE TITLE
Need to update Installation in README

### ISSUE THREAD

**Issue by Sparker0i** [MarkCLewis/SwiftVis2#5]
There's a point in the installation instructions which says: 

> Run ++2.11.12 to set the Scala version to 2.11. You can update the last value to whatever the latest release is. This is required because Spark currently doesn't work with Scala 2.12 or newer

The thing is I did a `publishToLocal` without setting `++2.11.12`, and I see that `swiftviz2spark_2.12` has been generated in my local:

![image](https://user-images.githubusercontent.com/14982488/80282777-fa8dd300-8730-11ea-8d93-35f618bf9e53.png)

Another thing is I don't see `swiftvis2_2.12` generated inside the same folder, so probably the instruction which says:
`libraryDependencies += "edu.trinity" %% "swiftvis2" % "0.1.0-SNAPSHOT"`
needs to be updated to:
`libraryDependencies += "edu.trinity" %% "swiftvis2core" % "0.1.0-SNAPSHOT"`

**Comment by MarkCLewis** [comment]
Thanks for the feedback. We've been focused on getting SwiftVis2 to work across multiple platforms and have fallen behind on the documentation. I'm about to push modifications to the README to address this and some other issues.
