### ISSUE TITLE
IDE error while trying Plot.scatterPlotGrid but code compiles just fine

### ISSUE THREAD

**Issue by Sparker0i** [MarkCLewis/SwiftVis2#6]
I am trying to plot a `Plot.scatterPlotGrid` using my Spark Dataset columns.

```
def plotData(): Unit = {
    implicit val ds = df

    val plot = Plot.scatterPlotGrid(
        Seq(
            Seq((doubles(ds, $"medv"), doubles(ds, $"crim"), BlackARGB, 5), ($"medv", $"crim", RedARGB, 5))
        ),
        "Plot Grid", "Shared X", "Shared Y"
    )

    SwingRenderer(plot)
}
```

**While this code compiles fine, and the program runs fine as well**, the IDE editor itself is showing me an error:

![Untitled](https://user-images.githubusercontent.com/14982488/80300236-8b5bc180-87b8-11ea-92fb-9e4661c03fc6.png)

**Comment by MarkCLewis** [comment]
This one is harder for me to help with other than to say that unfortunately most editors, including IntelliJ, occasionally show spurious errors. If it runs in sbt then the code is correct and the tool is just having problems. The same type of thing happens with Metals in VS Code. This gets more common as the projects get more complex and you bring in other libraries. I'm not certain what to recommend for this other than perhaps posting a minimal version as an issue for the IntelliJ Scala plugin. The fact that SwiftVis2 is currently not posted out to a Maven repository means that I don't know if they will take time to work with it. Getting it out there is definitely on my to-do list, but it hasn't made it to the top. I have started the process in the past, but I've run into enough resistance each time to prevent it from happening.
