### ISSUE TITLE
Java 8 required

### ISSUE THREAD

**Issue by fmarchand** [MarkCLewis/SwiftVis2#7]
I got into an issue.

Because the project use scalafx dependency 8.0.144-R12, I had to use java 8 jdk. But using ubuntu 20, I had to install manually the openjfx 8 packages (because it's not anymore in the apt repository and even on [JavaFX Download site](https://gluonhq.com/products/javafx/) you cannot find the version 8. 
OpenJdk 8 don't have the `jfxrt.jar` in `lib/ext` folder.

Do you think the upgrade to javafx 11 (scalaFX 11-R16) would be complicated ?   

I really like your library and I would love to use it in my projects.

Thx

**Comment by fmarchand** [comment]
I installed oracle jdk 8 and it works now. But still, jdk 8 is old ;)

**Comment by MarkCLewis** [comment]
I just pushed an update that moves it up to Java 11. It required a minor change in the Swing support (which is what I recommend using on the JVM) and more significant modifications for JavaFX because it is in a separate module.

**Comment by fmarchand** [comment]
I didn't see your message and was about to send the PR I did. I fetched the update and it works like a charm. Thanks a lot !

**Comment by MarkCLewis** [comment]
Spark 3.0.0 says it supports Java 11. It also supports Java 2.12 out of the box. I probably need to update the Spark version as well.
